### ISSUE TITLE
berlin meetup

### ISSUE THREAD

**Issue by ghost** [philipppahl/pydata_berlin#1]
Hey Phillip,

i missed the Berlin meetup.

I am working on ML with a startup, and was wondering if we could meet up in Berlin.

Regards

ged

**Comment by philipppahl** [comment]
Hi Ged,
sounds interesting. What kind of startup?
What can I help you with?
Best, Philipp

**Comment by ghost** [comment]
hey Phillip

i left the startup :) These days working on golang and machine learning
